m1 = csvread('/Users/mac/Desktop/programme/Python/renshen1/codes/csvs/sig_dan/dan6.csv', ...
                3,1,[3,1,1202,1]);
m2 = csvread('/Users/mac/Desktop/programme/Python/renshen1/codes/csvs/relu_dan/dan4.csv', ...
                3,1,[3,1,1202,1]);  
m3 = csvread('/Users/mac/Desktop/programme/Python/renshen1/codes/csvs/sig_relu/dan2.csv', ...
                3,1,[3,1,1202,1]);
m4 = csvread('/Users/mac/Desktop/programme/Python/renshen1/codes/csvs/relu_relu/dan2.csv', ...
                3,1,[3,1,1202,1]);  
m5 = csvread('/Users/mac/Desktop/programme/Python/renshen1/codes/csvs/relu_sig/dan1.csv', ...
                3,1,[3,1,1202,1]);
m6 = csvread('/Users/mac/Desktop/programme/Python/renshen1/codes/csvs/sig_sig/dan1.csv', ...
                3,1,[3,1,1202,1]);
x = [50:50:60000];

%plot(x,m1,'b-.',x,m2,'g-.',x,m3,'r-.',x,m4,'c-.');
%plot(x,m1,'b-',x,m2,'g-',x,m3,'r-');
%plot(x,m1,'b-',x,m2,'g-',x,m3,'r-',x,m4,'y-');
plot(x,m1,'b-',x,m2,'g-',x,m3,'r-',x,m4,'m-',x,m5,'y-',x,m6,'k-');
